# Generated by Django 3.2.5 on 2021-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='qty',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='items',
            name='saleprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
