# Generated by Django 3.2.5 on 2021-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210924_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='active',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
