# Generated by Django 3.2.5 on 2021-09-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210924_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemserials_details',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='itemcode',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='pricingbyID',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='pricingdate',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='saleprice',
        ),
        migrations.RemoveField(
            model_name='itemserials_details',
            name='unit',
        ),
        migrations.AlterField(
            model_name='itemserials_details',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterModelTable(
            name='itemserials_details',
            table='category',
        ),
    ]
