# Generated by Django 3.2.5 on 2021-10-18 01:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210929_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='brand',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='category',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='description',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='itemcode',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='pricingbyID',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='pricingdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='saleprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemserials_details',
            name='unit',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemserials_details',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterModelTable(
            name='itemserials_details',
            table='itemserials_details',
        ),
    ]
